### ISSUE TITLE
Fix Tensor to Numpy issue in InferenceInterfaces/FastSpeech2Interface.py file

### ISSUE THREAD

**Issue by bharaniyv** [DigitalPhonetics/IMS-Toucan#46] opened 2022-10-25 16:06 UTC
The inference file has a issue while using new enhancements, I think you forgot to add .cpu() at the end of wave.unsqueeze(0) in line 161 which is leading to the below error. Can you check once.
`File "/Desktop/IMS-Toucan/InferenceInterfaces/FastSpeech2Interface.py", line 161, in forward
    wave = enhance(self.enhancer, self.df, wave.unsqueeze(0), pad=True).squeeze()
TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.`

**Comment by Flux9665** [comment] 2022-10-25 16:22
Yes you are correct, thank you for pointing that out! I'll fix it right away.

**Comment by Flux9665** [comment] 2022-10-25 16:34
It's a bit weird of the deepfilternet API to expect tensors to be on CPU, even though the model has to be placed on GPU manually. I would have expected that I also place the tensor to the correct device manually. Anyway, the problem is fixed now. I tested it on CPU and GPU.

**Closed as completed by Flux9665** 2022-10-25 16:34 UTC

**Comment by bharaniyv** [comment] 2022-10-25 16:39
Thanks for the quick fix, But how good are new enhancement features compared to old noisereduce module, I just now tested few audio samples and I can see that there is still lot of noise in the output even after using enhancements which is not present in the V2.2 model, do you think the issue is with Vocoder or FastSpeech2 itself?

**Comment by Flux9665** [comment] 2022-10-26 20:28
The new speech enhancement method of using deepfilternet works a lot better than noisereduce in my tests, but yeah it also degrades the signal quite a bit because it also removes the natural sibillance in speech. I haven't found the perfect post-processing step for TTS yet. For some voices it is better to not use it, for some voices it is better to use it.

I believe most of the noise comes from the vocoder. I'll update the vocoder model in the release in the next few days with one that has trained for longer (training is still going on) and hope that that introduces less noise into the signal. I'm still optimizing hyperparameters and trying out new things with both FastSpeech and the Vocoder, hopefully I'll find the perfect setup sometime soon, I think I'm getting closer.
